vim.cmd("packloadall")

local config_dir = vim.fn.stdpath("config")

local function source(name)
  dofile(config_dir .. "/" .. name .. ".lua")
end

source("config")
source("keymap")
source("color")
source("lsp")
source("filetree")
source("bufferline")
source("toggleterm")
source("indentline")
source("fold")
source("lualine")
source("gitsigns")
source("autopairs")
source("comment")
source("telescope")
source("autosave")
source("refactoring")
source("spectre")
source("session")
source("dap")
source("harpoon")
source("local")
source("treesitter")
